### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by bandtank** [danielholmes/coc-base-analyser#1]
Two questions:
1. Does this code still work?
2. I am not familiar with JDK or SBT (I don't even know what this is). Are there any notes to help get started? Even a simple explanation would be nice.

**Comment by danielholmes** [comment]
Hi @bandtank ,

1. See the note about a Game Connection in the README: https://github.com/danielholmes/coc-base-analyser#game-connection . You need to source or code up a connection to the game servers as the one I was using isn't available any more. Whilst I haven't tried this project out in year, once you have this game connection there's no reason why it shouldn't work now still.

2. JDK is the Java Development Kit - A very popular programming/software platform. If you search google you'll better be able to pick out links that suit your knowledge/experience than I could for you. SBT is Scala Build Tool - https://www.scala-sbt.org/ . It will require programming knowledge to get running - it's not packaged into a nice end user executable or published to a website or anything like that

**Comment by bandtank** [comment]
Interesting. I tried to find the game connector you mentioned, but I can't find a trace of it anywhere. I'll see what I can figure out. Thanks.

**Comment by danielholmes** [comment]
@bandtank Some things to note about a connection like this:

- It's against the Supercell/Clash of Clans terms of service. So to find it might be difficult
- A connection like this is a cat and mouse game. At least when I was looking at it the protocols could change when a new update arrives, requiring changes in the programmed game connection

A related area are clash of clans private servers. Programming one of those includes some work related to a game connection, so looking for projects and/or people involved in those might be fruitful.
